/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _AddMoveRoute } from '../pages/add-move';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/add-move': (typeof _AddMoveRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/add-move': (typeof _AddMoveRoute)['_outputType'];
  }
}
